name: clang-tidy
on:
  push:
  pull_request:

permissions: {}

jobs:
  clang-tidy:
    # if: github.repository_owner == 'facebook'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 1
    - name: Mark workspace as safe for git
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - name: Save PR number
      if: github.event_name == 'pull_request' && always()
      run: |
        echo "${{ github.event.pull_request.number }}" > pr_number.txt
        echo "this is clang-tidy-comment.md" > clang-tidy-comment.md
    - name: Upload clang-tidy results
      if: always()
      uses: actions/upload-artifact@v4.0.0
      with:
        name: clang-tidy-result
        path: |
          clang-tidy-comment.md
          pr_number.txt
          .github/scripts/post-pr-comment.js
          mem-dump
